steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username='us1313' --password='Utsav@1313'']
#    secretEnv: ['USERNAME', 'PASSWORD']
#  - name: 'gcr.io/cloud-builders/docker'
#    entrypoint: 'bash'
#    args: ['-c', 'docker build -t $$us1313/test1']
#    secretEnv: ['USERNAME']
#  - name: 'gcr.io/cloud-builders/docker'
#    entrypoint: 'bash'
#    args: ['-c', 'docker push $$us1313/test1']
#    secretEnv: ['USERNAME']
#  availableSecrets:
#    secretManager:
#    - versionName: projects/alaric-365111/secrets/docker-password/versions/1
#      env: 'PASSWORD'
#    - versionName: projects/alaric-365111/secrets/docker-username/versions/1
#      env: 'USERNAME'
