 steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/test1:22 .']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/test1:22']
   secretEnv: ['USERNAME']
 availableSecrets:
   secretManager:
   - versionName: projects/alaric-365111/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/alaric-365111/secrets/docker-username/versions/1
     env: 'USERNAME'
